version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    environment:
      DB_USERNAME: username
      DB_PASSWORD: password
volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge